---
title: "Final_Project"
author: "Ananya, Rosie, Sameer"
date: '2025-04-04'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#Set working directory
knitr::opts_knit$set(root.dir = "/Users/sameerswarup/Documents/Duke MEM Classes/Spring 2025/Time Series Analysis for Energy/RStudio Outputs/Final_Project")
```

```{r, message= FALSE}
#Load libraries
library(tidyverse)
library(forecast)
library(tseries)
library(sarima)
library(lubridate)
library(Kendall)
library(outliers)
library(foreign)
library(here)
```

```{r}
#Import wave energy dataset
here()
getwd()
alaska_df <- read.csv("../Data/Alaska_combined_output.csv",
                      skip = 2,
                      header = TRUE)
florida_df <- read.csv("../Data/Florida_combined_output.csv",
                      skip = 2,
                      header = TRUE)
maine_df <- read.csv("../Data/Gulf of Maine_combined_output.csv",
                      skip = 2,
                      header = TRUE)
```

```{r}
# Data wrangling needed: create timestamps (sum hourly to daily),
# Add Wave Energy column: Formula for Wave Energy Flux = Wave Power Density * Wave Energy Period
# Data Exploration: just graph the Wave Energy Flux original series data comparison between the 3 sites.
# Run original TS, ACF, PACF
# Trains models: people tend to use the SARIMA, ARIMA Fourier, STL+ETS, TBATS, 

## state space model can eliminate the impact of outliers
```

